### ISSUE TITLE
附带部分建议

### ISSUE THREAD

**Issue by zxcv1129678576** [Tencent/FAutoTest#2]
1.未指明pip镜像地址，https://git.code.tencent.com/Tencent_Open_Source/FAutoTest
目前其他源暂时没有FAutoTest。建议备注下哈。对萌新不是很友好。。。
2.demo目前跑通了h5的，qq和小程序的还在尝试中。

**Comment by Chrisdimion** [comment]
恩 目前主要的源只有两个，一个当前的github, 一个是你所指的工蜂网，工蜂网是为了防止有些小伙伴github访问不了而作为备选的。若后续会进行镜像地址的更新，会进行公告回复。

**Comment by zxcv1129678576** [comment]
thanks
