### ISSUE TITLE
是否可用提供端口和环境

### ISSUE THREAD

**Issue by jimmyseraph** [Tencent/FAutoTest#6]
微信小程序测试现在一直是在真机上，现在微信小程序开发越来越多，像这样一个基于`WebDriver`框架的`python`程序，来应用在真机上面进行测试，其实完全没有给出预期的解决方案。仅仅在真机上用`WebDriver`进行测试，绝大多数公司都能做，并不解决痛点。微信小程序测试要解决的痛点，是在微信账号和真机有限的情况下，如何部署数十甚至几十个微信小程序的自动化测试。
希望*tx*给出新的测试环境，类似于小程序开发者工具那种IDE，只不过这个环境是用于测试的，让微信小程序测试不必依赖微信，提供一个微信虚拟机环境，这样能够真实的解决小程序测试痛点。如果能在DockerHub上提供微信虚拟机环境的Docker，那就功德无量了。
而这个仓库所提供的FAutoTest，价值真的太低了。

**Comment by Chrisdimion** [comment]
我们也在一直探讨小程序的自动化测试，目前这个框架解决的是将业务人工测试转化为自动化测试流程。比如说你用一台真机一个帐户同时部署数十甚至几十个微信小程序，剔除安全影响，是属于相对理想的自动化测试状态，当然用这个框架是可以转为同步来测试，但是一般来说，小程序就跟微信帐户绑定，剔除掉微信的帐号，不依赖于微信环境，但后台的真实的数据无法用虚拟环境去获取。当然，若有好的idea，欢迎跟我们联系。
