### ISSUE TITLE
建议把 weixin.apk 放到其它地方，不要放在仓库中，会导致 clone 仓库的时候巨慢

### ISSUE THREAD

**Issue by LucianLiu6** [Tencent/FAutoTest#9]
建议把 `/docs/assert/weixin663android1260.apk` 这个 apk 独立出来放到一些在线云存储上去，不然 clone 仓库的时候可能会由于 `git-lfs` 导致速度很慢  
我这边在本地 clone 的速度只有 `20kb/s`...  
只不过放进去之后要再拿出来感觉会比较麻烦，而且这个 apk 还是和其它文件一起在 `a0a065b` 第一个 commit 提交上去的，有点难分离...

**Comment by Chrisdimion** [comment]
暂时不考虑进行分离，感谢建议
